#pragma once

#include"Node.hpp"
#include"infix.hpp"
#include"integer.hpp"
#include"program.hpp"
#include"expression_statement.hpp"
#include"bool.hpp"
#include"prefix.hpp"
#include"mstring.hpp"
#include"declaration.hpp"
#include"identifier.hpp"
#include"know.hpp"
#include"output.hpp"
#include"infer.hpp"
#include"block.hpp"
#include"if.hpp"
#include"while.hpp"
#include"for.hpp"
#include"func.hpp"